//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDde.Properties
{
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nDDE.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The server failed to advise &quot;${service}|${topic}!${item}&quot;. ähnelt.
        /// </summary>
        public static string AdviseFailedMessage {
            get {
                return ResourceManager.GetString("AdviseFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An advise loop for &quot;${service}|${topic}!${item}&quot; already exists. ähnelt.
        /// </summary>
        public static string AlreadyBeingAdvisedMessage {
            get {
                return ResourceManager.GetString("AlreadyBeingAdvisedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client is already connected. ähnelt.
        /// </summary>
        public static string AlreadyConnectedMessage {
            get {
                return ResourceManager.GetString("AlreadyConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The context is already intialized. ähnelt.
        /// </summary>
        public static string AlreadyInitializedMessage {
            get {
                return ResourceManager.GetString("AlreadyInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified conversation is already paused. ähnelt.
        /// </summary>
        public static string AlreadyPausedMessage {
            get {
                return ResourceManager.GetString("AlreadyPausedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The service is already registered. ähnelt.
        /// </summary>
        public static string AlreadyRegisteredMessage {
            get {
                return ResourceManager.GetString("AlreadyRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The IAsyncResult must have been returned by a call to ${method}. ähnelt.
        /// </summary>
        public static string AsyncResultParameterInvalidMessage {
            get {
                return ResourceManager.GetString("AsyncResultParameterInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client failed to pause the conversation. ähnelt.
        /// </summary>
        public static string ClientPauseFailedMessage {
            get {
                return ResourceManager.GetString("ClientPauseFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client failed to resume the conversation. ähnelt.
        /// </summary>
        public static string ClientResumeFailedMessage {
            get {
                return ResourceManager.GetString("ClientResumeFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client failed to connect to &quot;${service}|${topic}&quot;.  Make sure the server application is running and that it supports the specified service name and topic name pair. ähnelt.
        /// </summary>
        public static string ConnectFailedMessage {
            get {
                return ResourceManager.GetString("ConnectFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client failed to execute &quot;${command}&quot;. ähnelt.
        /// </summary>
        public static string ExecuteFailedMessage {
            get {
                return ResourceManager.GetString("ExecuteFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The transaction filter has already been added. ähnelt.
        /// </summary>
        public static string FilterAlreadyAddedMessage {
            get {
                return ResourceManager.GetString("FilterAlreadyAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The transaction filter has not been added. ähnelt.
        /// </summary>
        public static string FilterNotAddedMessage {
            get {
                return ResourceManager.GetString("FilterNotAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The context failed to initialize. ähnelt.
        /// </summary>
        public static string InitializeFailedMessage {
            get {
                return ResourceManager.GetString("InitializeFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The context timed out attempting to marshal the operation. ähnelt.
        /// </summary>
        public static string MarshalTimeoutMessage {
            get {
                return ResourceManager.GetString("MarshalTimeoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The context is not hosted on a thread with a message loop. ähnelt.
        /// </summary>
        public static string NoMessageLoopMessage {
            get {
                return ResourceManager.GetString("NoMessageLoopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An advise loop for &quot;${service}|${topic}!${item}&quot; does not exist. ähnelt.
        /// </summary>
        public static string NotBeingAdvisedMessage {
            get {
                return ResourceManager.GetString("NotBeingAdvisedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client is not connected. ähnelt.
        /// </summary>
        public static string NotConnectedMessage {
            get {
                return ResourceManager.GetString("NotConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The context is not initialized. ähnelt.
        /// </summary>
        public static string NotInitializedMessage {
            get {
                return ResourceManager.GetString("NotInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified conversation is not paused. ähnelt.
        /// </summary>
        public static string NotPausedMessage {
            get {
                return ResourceManager.GetString("NotPausedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The service is not registered. ähnelt.
        /// </summary>
        public static string NotRegisteredMessage {
            get {
                return ResourceManager.GetString("NotRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client failed to poke &quot;${service}|${topic}!${item}&quot;. ähnelt.
        /// </summary>
        public static string PokeFailedMessage {
            get {
                return ResourceManager.GetString("PokeFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The server failed to register &quot;${service}&quot;. ähnelt.
        /// </summary>
        public static string RegisterFailedMessage {
            get {
                return ResourceManager.GetString("RegisterFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client failed to request &quot;${service}|${topic}!${item}&quot;. ähnelt.
        /// </summary>
        public static string RequestFailedMessage {
            get {
                return ResourceManager.GetString("RequestFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The server failed to pause all conversations. ähnelt.
        /// </summary>
        public static string ServerPauseAllFailedMessage {
            get {
                return ResourceManager.GetString("ServerPauseAllFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The server failed to pause the specified conversation. ähnelt.
        /// </summary>
        public static string ServerPauseFailedMessage {
            get {
                return ResourceManager.GetString("ServerPauseFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The server failed to resume all conversations. ähnelt.
        /// </summary>
        public static string ServerResumeAllFailedMessage {
            get {
                return ResourceManager.GetString("ServerResumeAllFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The server failed to resume the specified conversation. ähnelt.
        /// </summary>
        public static string ServerResumeFailedMessage {
            get {
                return ResourceManager.GetString("ServerResumeFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client failed to initiate an advise loop for &quot;${service}|${topic}!${item}&quot;. ähnelt.
        /// </summary>
        public static string StartAdviseFailedMessage {
            get {
                return ResourceManager.GetString("StartAdviseFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The client failed to terminate the advise loop for &quot;${service}|${topic}!${item}&quot;. ähnelt.
        /// </summary>
        public static string StopAdviseFailedMessage {
            get {
                return ResourceManager.GetString("StopAdviseFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The parameter must be &lt;= 255 characters. ähnelt.
        /// </summary>
        public static string StringParameterInvalidMessage {
            get {
                return ResourceManager.GetString("StringParameterInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The parameter must be &gt; 0. ähnelt.
        /// </summary>
        public static string TimeoutParameterInvalidMessage {
            get {
                return ResourceManager.GetString("TimeoutParameterInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unknown error occurred. ähnelt.
        /// </summary>
        public static string UnknownErrorMessage {
            get {
                return ResourceManager.GetString("UnknownErrorMessage", resourceCulture);
            }
        }
    }
}
